site_name: Slim Framework
pages:
    - [index.md, 主页]
    - [start/installation.md, Get Started, 安装]
    - [start/web-servers.md, Get Started, Web 服务器]
    - [concepts/objects.md, Concepts, Objects]
    - [concepts/di.md, Concepts, 依赖注入]
    - [concepts/middleware.md, Concepts, 中间件]
    - [concepts/value-objects.md, Concepts, Value Objects]
    - [concepts/life-cycle.md, Concepts, 生命周期]
    - [objects/environment.md, Objects, 环境]
    - [objects/request.md, Objects, 请求]
    - [objects/response.md, Objects, 响应]
    - [objects/router.md, Objects, 路由器]
    - [features/templates.html, 特性, 视图 and 模板]
    - [caching.md, 缓存]
    - [handlers/error.md, Error Handling, 500 Server Error]
    - [handlers/not-found.md, Error Handling, 404 Not Found]
    - [handlers/not-allowed.md, Error Handling, 405 Not Allowed]
    - [contributors/strategy.md, Contributors, Branching Strategy]
theme: readthedocs
markdown_extensions: [markdown.extensions.extra]
