site_name: Slim 3.0 中文文档
pages:
    - [index.md, 主页]
    - [start/installation.md, 开始, 安装]
    - [start/web-servers.md, 开始, Web 服务器]
    - [concepts/objects.md, 基本概念, 对象]
    - [concepts/di.md, 基本概念, 依赖注入]
    - [concepts/middleware.md, 基本概念, 中间件]
    - [concepts/value-objects.md, 基本概念, 值对象]
    - [concepts/life-cycle.md, 基本概念, 生命周期]
    - [objects/environment.md, 对象, 环境]
    - [objects/request.md, 对象, 请求]
    - [objects/response.md, 对象, 响应]
    - [objects/router.md, 对象, 路由器]
    - [features/templates.html, 特性, 视图和模板]
    - [caching.md, 缓存]
    - [handlers/error.md, 错误处理, 500 Server Error]
    - [handlers/not-found.md, 错误处理, 404 Not Found]
    - [handlers/not-allowed.md, 错误处理, 405 Not Allowed]
    - [contributors/strategy.md, 贡献者, 分支策略]
theme: readthedocs
markdown_extensions: [markdown.extensions.extra]
